# @package agent
_target_: agents.algorithms.sac.SACAgent
name: sac
reward_free: ${reward_free}
nstep : 1
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-3
feature_dim : 50
hidden_dim: 1024
critic_target_tau: 0.01
num_expl_steps: ??? # to be specified later
batch_size: 256 # 512 for pixels, 1024 for states
init_critic: true
use_tb: ${use_tb}
use_wandb: ${use_wandb}
log_std_min : -10
log_std_max : 2
init_temperature : 0.1
actor_update_frequency : 2
critic_target_update_frequency : 2


#update_encoder: ${update_encoder}